version: "3"

tasks:
  build-image:
    internal: true
    sources:
      - scripts/**/Dockerfile
    status:
      - docker image inspect {{.IMAGE_NAME}}
    cmds:
      - >-
        docker build
        --platform {{.DOCKER_PLATFORM}}
        --build-arg UID=$UID --build-arg GID=$GID
        {{default "" .CACHE_ARGS}}
        -t {{.IMAGE_NAME}}
        {{.DOCKERFILE}}

  build-app:
    internal: true
    cmds:
      - task: run
        vars:
          IMAGE_NAME: "{{.IMAGE_NAME}}"
          DOCKER_PLATFORM: "{{.DOCKER_PLATFORM}}"
          PLATFORM: "{{.PLATFORM}}"
          APP_BIN: "{{.APP_BIN}}"
          EXEC: '{{default "task build" .EXEC}}'
          EXTRA_DOCKER_ARGS: '{{default "" .EXTRA_DOCKER_ARGS}}'

  run:
    internal: true
    vars:
      BUILDCACHE: '{{if eq OS "windows"}}{{.LOCALAPPDATA}}\\go-build{{else}}{{.HOME}}/.cache/go-build{{end}}'
      GOCACHE: '{{if eq OS "windows"}}{{.USERPROFILE}}\\go{{else}}{{.HOME}}/go{{end}}'
      IMG_BUILDCACHE: /home/build/.cache/go-build
      IMG_GOCACHE: /home/build/go
    cmds:
      - '{{if eq OS "windows"}}cmd /c if not exist "{{.BUILDCACHE}}" mkdir "{{.BUILDCACHE}}"{{else}}mkdir -p "{{.BUILDCACHE}}"{{end}}'
      - '{{if eq OS "windows"}}cmd /c if not exist "{{.GOCACHE}}" mkdir "{{.GOCACHE}}"{{else}}mkdir -p "{{.GOCACHE}}"{{end}}'
      - >-
        docker run --rm
        --platform {{.DOCKER_PLATFORM}}
        -v "{{.BUILDCACHE}}:{{.IMG_BUILDCACHE}}"
        -v "{{.GOCACHE}}:{{.IMG_GOCACHE}}"
        -v "${PWD}:/build"
        -e PLATFORM={{.PLATFORM}}
        -e APP_BIN={{.APP_BIN}}
        {{.EXTRA_DOCKER_ARGS}}
        {{.IMAGE_NAME}} {{.EXEC}}