version: "3"

tasks:
  setup:
    cmds:
      - task: :docker:build-image
        vars:
          IMAGE_NAME: zaparoo/zigcc-build
          DOCKERFILE: "./scripts/zigcc"

  build-arm64:
    cmds:
      - task: :build
        vars:
          BUILD_OS: darwin
          BUILD_ARCH: arm64
          PLATFORM: mac
          APP_BIN: zaparoo
          NO_LIBNFC: true
          NO_STATIC: true

  build-amd64:
    cmds:
      - task: :build
        vars:
          BUILD_OS: darwin
          BUILD_ARCH: amd64
          PLATFORM: mac
          APP_BIN: zaparoo
          NO_LIBNFC: true
          NO_STATIC: true
