version: "3"

tasks:
  build-app:
    cmds:
      - rm -rf "./_build/mac_{{.BUILD_ARCH}}/Zaparoo Core.app"
      - cp -r "./cmd/mac/app/Zaparoo Core.app" "./_build/mac_{{.BUILD_ARCH}}/Zaparoo Core.app"
      - cp ./_build/mac_{{.BUILD_ARCH}}/zaparoo "./_build/mac_{{.BUILD_ARCH}}/Zaparoo Core.app/Contents/MacOS/Zaparoo Core"

  build-arm64:
    cmds:
      - task: :build-basic
        vars:
          BUILD_OS: darwin
          BUILD_ARCH: arm64
          PLATFORM: mac
          APP_BIN: zaparoo
          CGO_ENABLED: 1
      - task: build-app
        vars:
          BUILD_ARCH: arm64

  build-amd64:
    cmds:
      - task: :build-basic
        vars:
          BUILD_OS: darwin
          BUILD_ARCH: amd64
          PLATFORM: mac
          APP_BIN: zaparoo
          CGO_ENABLED: 1
      - task: build-app
        vars:
          BUILD_ARCH: amd64

  dev:
    cmds:
      - air --build.cmd "task mac:build-{{.CLI_ARGS}}" --build.bin "./_build/mac_{{.CLI_ARGS}}/zaparoo -daemon"