version: "3"

tasks:
  setup-arm64:
    internal: true
    cmds:
      - task: :docker:build-image
        vars:
          IMAGE_NAME: zaparoo/linux-arm64-build
          DOCKERFILE: "./scripts/linux_arm64"
          DOCKER_PLATFORM: linux/arm64/v8

  build-arm64:
    cmds:
      - task: setup-arm64
      - task: :docker:build-app
        vars:
          PLATFORM: mistex
          BUILD_ARCH: arm64
          DOCKER_PLATFORM: linux/arm64/v8
          IMAGE_NAME: zaparoo/linux-arm64-build
          APP_BIN: zaparoo.sh

  deploy-arm64:
    cmds:
      - task: build-arm64
      - scp _build/mistex_arm64/zaparoo.sh root@${MISTEX_IP}:/media/fat/Scripts/zaparoo.sh
      - ssh root@${MISTEX_IP} /media/fat/Scripts/zaparoo.sh -service restart