version: "3"

tasks:
  setup-arm:
    internal: true
    cmds:
      - task: :docker:build-image
        vars:
          IMAGE_NAME: zaparoo/linux-arm-build
          DOCKERFILE: "./scripts/linux_arm/build"
          ARCH: arm/v7

  build-arm:
    cmds:
      - task: setup-arm
      - task: :docker:build-app
        vars:
          PLATFORM: mister
          BUILD_ARCH: arm
          DOCKER_ARCH: arm/v7
          IMAGE_NAME: zaparoo/linux-arm-build
          APP_BIN: zaparoo.sh

  deploy-arm:
    cmds:
      - task: build-arm
      - scp _build/mister_arm/zaparoo.sh root@${MISTER_IP}:/media/fat/Scripts/zaparoo.sh
      - ssh root@${MISTER_IP} /media/fat/Scripts/zaparoo.sh -service restart