version: "3"

tasks:
  setup-amd64:
    internal: true
    cmds:
      - task: :docker:build-image
        vars:
          IMAGE_NAME: zaparoo/linux-amd64-build
          DOCKERFILE: "./scripts/linux_amd64"
          DOCKER_PLATFORM: linux/amd64

  build-amd64:
    cmds:
      - task: setup-amd64
      - task: :docker:build-app
        vars:
          PLATFORM: steamos
          BUILD_ARCH: amd64
          DOCKER_PLATFORM: linux/amd64
          IMAGE_NAME: zaparoo/linux-amd64-build
          APP_BIN: zaparoo

  deploy-amd64:
    cmds:
      - task: build-amd64
      - scp _build/steamos_amd64/zaparoo deck@${STEAMOS_IP}:/home/deck/zaparoo/zaparoo