version: "3"

tasks:
  build:
    cmds:
      - task: :build
        vars:
          PLATFORM: testscanner
          IMAGE_NAME: zaparoo/cross-build
          NO_LIBNFC: true
          NO_STATIC: true

  dev:
    cmds:
      - air --build.cmd "task test:build" --build.bin "./_build/testscanner_{{ARCH}}/zaparoo"
