version: "3"

tasks:
  build-metadata:
    internal: true
    cmds:
      - go run scripts/tasks/utils/windowsmeta.go -version "${APP_VERSION}"
      - task: :docker:run
        vars:
          IMAGE_NAME: zaparoo/cross-build
          EXEC: sh -c 'cd cmd/windows && go-winres make --arch="amd64,arm64,386"'

  build-installer:
    internal: true
    cmds:
      - go run scripts/tasks/utils/windowsiss.go -version "${APP_VERSION}" -arch "{{ARCH}}"
      - cp "cmd/windows/winres/icon.ico" "_build/windows_{{ARCH}}"
      - >-
        docker run --rm -i -v "${PWD}:/work" 
        amake/innosetup 
        "_build/windows_{{.BUILD_ARCH}}/setup.iss"

  setup:
    internal: true
    cmds:
      - task: :docker:build-image
        vars:
          IMAGE_NAME: zaparoo/cross-build
          DOCKERFILE: scripts/cross

  build-arm64:
    cmds:
      - task: setup
      - task: build-metadata
      - task: :docker:build-app
        vars:
          BUILD_OS: windows
          BUILD_ARCH: arm64
          PLATFORM: windows
          IMAGE_NAME: zaparoo/cross-build
          NO_LIBNFC: true
          APP_BIN: Zaparoo.exe
          EXTRA_LDFLAGS: -H=windowsgui
          CC: zig cc -w --target=aarch64-windows-gnu
          CXX: zig c++ -w --target=aarch64-windows-gnu

  build-amd64:
    cmds:
      - task: setup
      - task: build-metadata
      - task: :docker:build-app
        vars:
          BUILD_OS: windows
          BUILD_ARCH: amd64
          PLATFORM: windows
          IMAGE_NAME: zaparoo/cross-build
          NO_LIBNFC: true
          APP_BIN: Zaparoo.exe
          EXTRA_LDFLAGS: -H=windowsgui
          CC: x86_64-w64-mingw32-gcc
          CXX: x86_64-w64-mingw32-g++
      - task: build-installer
        vars:
          BUILD_ARCH: amd64

  build-386:
    cmds:
      - task: setup
      - task: build-metadata
      - task: :docker:build-app
        vars:
          BUILD_OS: windows
          BUILD_ARCH: 386
          PLATFORM: windows
          IMAGE_NAME: zaparoo/cross-build
          NO_LIBNFC: true
          APP_BIN: Zaparoo.exe
          EXTRA_LDFLAGS: -H=windowsgui
          CC: i686-w64-mingw32-gcc-win32
          CXX: i686-w64-mingw32-g++-win32
