version: "3"

tasks:
  build-arm64:
    cmds:
      - task: :build
        vars:
          BUILD_OS: windows
          BUILD_ARCH: arm64
          PLATFORM: windows
          APP_BIN: Zaparoo.exe
          NO_LIBNFC: true
          EXTRA_LDFLAGS: -H=windowsgui

  build-amd64:
    cmds:
      - task: :build
        vars:
          BUILD_OS: windows
          BUILD_ARCH: amd64
          PLATFORM: windows
          APP_BIN: Zaparoo.exe
          NO_LIBNFC: true
          EXTRA_LDFLAGS: -H=windowsgui