version: "3"

tasks:
  build-arm64:
    cmds:
      - task: :build-basic
        vars:
          BUILD_OS: windows
          BUILD_ARCH: arm64
          GOOS: windows
          PLATFORM: windows
          APP_BIN: Zaparoo.exe
          CGO_ENABLED: 0
          BUILD_ARGS: -ldflags "-H=windowsgui"

  build-amd64:
    cmds:
      - task: :build-basic
        vars:
          BUILD_OS: windows
          BUILD_ARCH: amd64
          GOOS: windows
          PLATFORM: windows
          APP_BIN: Zaparoo.exe
          CGO_ENABLED: 0
          BUILD_ARGS: -ldflags "-H=windowsgui"