name: Build and Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Specify the tag for the release'
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image for ARM
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm/v7 -t mrext/armbuild:${{ github.sha }} -f scripts/armbuild/Dockerfile .

      - name: Run mage prepRelease
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace mrext/armbuild:${{ github.sha }} mage build prepRelease

#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.event.inputs.tag }}
#          release_name: Release ${{ github.event.inputs.tag }}
#          body: |
#            Release notes and details go here.
#          draft: true
#
#      - name: Upload release assets
#        id: upload-release-asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ./_bin/releases/*
#          asset_name: ${{ github.event.inputs.tag }}-${{ env.OS_NAME }}-${{ env.OS_ARCH }}-${{ github.sha }}-${{ github.run_number }}
#          asset_content_type: application/octet-stream
