name: Generate MiSTer latest repo
on:
  workflow_dispatch:

permissions: write-all
jobs:
  mister-repo:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - name: Get latest TapTo release
        id: taptoreleaseinfo
        uses: cardinalby/git-get-release-action@v1
        with:
          latest: true
          repo: wizzomafizzo/tapto
          ref: main
      - name: Download release files
        run: |
          DL_URL=https://github.com/wizzomafizzo/tapto/releases/download/${{ steps.taptoreleaseinfo.outputs.tag_name }}
          mkdir -p _bin/releases
          curl -L ${DL_URL}/tapto.sh -o _bin/releases/tapto.sh
          curl -L ${DL_URL}/taptui.sh -o _bin/releases/taptui.sh
      - name: Create databases
        run: |
          python scripts/mister/repo/generate.py ${{ steps.taptoreleaseinfo.outputs.tag_name }}
      - name: Commit databases
        uses: EndBug/add-and-commit@v9
        with:
          add: scripts/mister/repo/tapto.json -f -A